# Generated by Django 5.2 on 2025-06-14 10:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(default=app.models.generate_order_reference, max_length=255, verbose_name='Order Reference'),
        ),
    ]
